import{a as u,i,S as p}from"./assets/vendor-D5mnuR-h.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const m="49355863-0bea5bd004f89622601c6cae0",y="https://pixabay.com/api/";async function f(s){try{return(await u.get(y,{params:{key:m,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}catch(t){return console.error("Sorry, there are no images matching your search query. Please try again!",t),i.error({title:"❌ Error",message:"Something went wrong!",position:"topRight"}),[]}}let c;function g(s){const t=document.querySelector(".gallery");t.innerHTML="",s.forEach(r=>{const n=document.createElement("li");n.classList.add("gallery-item"),n.innerHTML=`
        <a href="${r.largeImageURL}" class="gallery-link">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy"/>
        </a>
        <div class="info">
          <p>Likes: ${r.likes}</p>
          <p>Views: ${r.views}</p>
          <p>Comments: ${r.comments}</p>
          <p>Downloads: ${r.downloads}</p>
        </div>
      `,t.appendChild(n)}),c?c.refresh():c=new p(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250})}const d=document.querySelector(".form"),h=document.querySelector(".gallery"),a=document.createElement("div");a.classList.add("loader");document.body.appendChild(a);d.addEventListener("submit",async s=>{s.preventDefault();const t=d.elements["search-text"].value.trim();if(t===""){i.error({title:"❌ Error",message:"Please enter a search query!",position:"topRight"});return}a.style.display="block",h.innerHTML="";try{const r=await f(t);r.length===0?i.error({title:"❌ No images found",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):g(r)}catch(r){i.error({title:"❌ Error",message:"Something went wrong while fetching images!",position:"topRight"}),console.error("Error fetching images:",r)}finally{a.style.display="none"}});
//# sourceMappingURL=index.js.map
